algoritmo "semnome"
// Função :
// Autor :
// Data : 10/11/2017
// Seção de Declarações 
var
   quanto,salto,contador: inteiro
inicio
      contador <- 0
      Escreva ("Quer contar até quanto? ")
      Leia (quanto)
      Escreva ("Qual o salto? ")
      Leia (salto)
      Enquanto (contador <= quanto) faca
        Escreval(contador)
          contador <- contador + salto
      fimEnquanto
      Escreval ("TERMINEI DE CONTAR!!!")
fimalgoritmo
