algoritmo "Exercício 5 cap 9"
// Função :
// Autor :
// Data : 17/10/2017
// Seção de Declarações 
var
   nome: caractere
   km,tempo,v: real
inicio
      Escreva ("Digite seu nome: ")
      Leia (nome)
      Escreva ("Distância percorrida [km]: ")
      Leia (km)
      Escreva ("Informe o tempo [horas]: ")
      Leia (tempo)
      v <- km/tempo
      Escreva ("A velocidade média do ",nome," foi",v," km/h")
      
fimalgoritmo
