algoritmo "semnome"
// Função :
// Autor :
// Data : 05/10/2017
// Seção de Declarações 
var
  nome: caractere
  n1,n2,s: real
inicio
      Escreva ("Olá, qual o seu nome? ")
      Leia (nome)
      Escreval ("seja bem vindo(a) ",nome)
      Escreval ("Vamos somar dois números.")
      Escreva ("Digite um número: ")
      Leia (n1)
      Escreva("Digite outro número: ")
      Leia (n2)
      s <- (n1+n2)
      Escreva ("A soma será de",s," unidades!")
fimalgoritmo
