algoritmo "semnome"
// Função :
// Autor :
// Data : 06/02/2018
// Seção de Declarações 
var
   m: vetor [1..5,1..5] de inteiro
   l,c: inteiro
inicio
      Para l<-1 ate 5 faca
          Para c<-1 ate 5 faca
               Leia (m[l,c])
          FimPara
      FimPara
      LIMPATELA
      Para l<-1 ate 5 faca
          Para c<-1 ate 5 faca
               Escreva (m[l,c]:4)
          FimPara
          Escreval ()
      FimPara
fimalgoritmo
